### ISSUE TITLE
cablecast_sync_schedule doesn't delete schedule events on anonymous cron run

### ISSUE THREAD

**Issue by patdunlavey** [raytiley/Cablecast-Drupal-Module#6]
node_delete checks for permissions before deleting nodes. When cron runs (as user 0), sync_schedule can't delete nodes. My solution was to create my own cablecast_node_delete function that leaves out the permission checking. I'm not sure if that's the right way to do this!

http://api.drupal.org/api/drupal/modules--node--node.module/function/node_delete/6

**Comment by raytiley** [comment]
Pat,

That makes a lot of sense.  I was wondering why I was getting duplicate entries on my schedule that would be deleted once I ran cron.

Rather than writing a seperate function, what I'll do is flush out the permissions and add delete access to user 0 if being called by cron.

I'll was planning on doing some coding on this tomorrow.

**Comment by patdunlavey** [comment]
Would this be the right way?
http://drupal.org/node/218104

**Comment by raytiley** [comment]
That looks perfect.

I couldn't think of a way to determine if node_delete was being called from cron, so I just did it as outlined in above link.

**Comment by patdunlavey** [comment]
I like your approach of bracketing the entire cron function. It's working for me.
